language: ruby
rvm:
- 2.5
script: "./script/cibuild"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
sudo: false
cache: bundler
notifications:
  email: false
before_install:
- openssl aes-256-cbc -K $encrypted_a6749ada6b62_key -iv $encrypted_a6749ada6b62_iv -in blog-deploy-key.enc -out blog-deploy-key -d
