#!/bin/bash

set -x

# Initialize a new git repo in _site, and push it to our server.
cd _site
git init

git remote add deploy "ssh://travis@138.68.27.163/var/www/.blog_build/blog"
git config user.name "Travis CI"
git config user.email "john@yeliad.us"

git add .
git commit -m "Deploy"
git push --force deploy master
