#!/bin/bash
set -x # Show the output of the following commands (useful for debugging)

# Import the SSH deployment key
openssl aes-256-cbc -K $encrypted_a6749ada6b62_key -iv $encrypted_a6749ada6b62_iv -in blog-deploy-key.enc -out blog-deploy-key -d
rm blog-deploy-key.enc # Don't need it anymore
chmod 600 blog-deploy-key
mv blog-deploy-key ~/.ssh/id_rsa
